package tests.USVTest;

import org.openqa.selenium.JavascriptExecutor;
import org.testng.Assert;
import org.testng.annotations.Test;
import pages.SeleniumEasyPages.EmailVerificationPage;
import pages.USVPages.*;
import sun.plugin.viewer.AxBridgeObject;
import utilities.BrowserUtils;
import utilities.USVTestBase;

import java.sql.SQLOutput;
import java.util.Set;

public class USVHomePage extends USVTestBase {

    TermsAndConditionsPage termsAndConditionsPage = new TermsAndConditionsPage();
    LoginPage loginPage = new LoginPage();
    EmailVerificationPageUSV emailVerificationPageUSV = new EmailVerificationPageUSV();
    AccountDetailsPage accountDetailsPage = new AccountDetailsPage();
    ActivateCardPage activateCardPage = new ActivateCardPage();
    ManageCardPage manageCardPage = new ManageCardPage();
    EmailVerificationPage emailVerificationPage = new EmailVerificationPage();
    GooglePage googlePage = new GooglePage();
    GeneratorEmail generatorEmail = new GeneratorEmail();
    CustomizeMyCardPage customizeMyCardPage = new CustomizeMyCardPage();
    DirectDepositPage directDepositPage = new DirectDepositPage();
    FeedbackPage feedbackPage = new FeedbackPage();
    PayBillsPage payBillsPage = new PayBillsPage();
    TransferFundsPage transferFundsPage =  new TransferFundsPage();
    ProfilePage profilePage= new ProfilePage();

    @Test
    public void ActivateCard() {
        String username = "moseloway1900@gmail.com";
        String password = "Welcome!1";
        String lastFour = "5894";
        String Expiration = "0222";
        String googlePassword = "Taylor!24680";
        String keys = "1445";
        BrowserUtils.waitFor(10);
        termsAndConditionsPage.clickRadioButton();
        termsAndConditionsPage.clickContinueButton();
        loginPage.clickEmailTextBox(username);
        loginPage.clickPasswordTextBox(password);
        BrowserUtils.waitFor(5);
        loginPage.clickSignInButton();
        BrowserUtils.waitFor(15);
        loginPage.clickSendVerification();
        ((JavascriptExecutor) driver).executeScript("window.open('https://www.google.com/?authuser=1')");
        BrowserUtils.waitFor(10);
        Set<String> handles = driver.getWindowHandles();
        String firstWindowhandle = driver.getWindowHandle();
        System.out.println(firstWindowhandle);
        handles.remove(firstWindowhandle);
        String winHandle = handles.iterator().next();
        String secondWindowhandle = winHandle;
        driver.switchTo().window(secondWindowhandle);
        System.out.println(secondWindowhandle);
        googlePage.clickSignInButton();
        BrowserUtils.waitFor(3);
        googlePage.enterEmail(username);
        googlePage.clickNextButton();
        googlePage.enterPassword(googlePassword);
        googlePage.clickNextButtonTwo();
        googlePage.clickAppsIcon();
        driver.switchTo().frame(0);
        googlePage.clickGmailIcon();
        googlePage.clickVerificationEmail();
        BrowserUtils.waitFor(4);
        googlePage.clickEmail(); //might move
        BrowserUtils.waitFor(3);
        emailVerificationPage.clickVerifyEmailButton();
        driver.switchTo().window(firstWindowhandle);
        BrowserUtils.waitFor(25);
        accountDetailsPage.clickagainHamburgerMenu();
        accountDetailsPage.clickManageCardButton();
        manageCardPage.clickActivateCard();
        activateCardPage.enterLastfourdigitsofCardTextBox(lastFour);
        activateCardPage.entercardExpirationTextBox(Expiration);
        activateCardPage.clickActivateCardButton();
        BrowserUtils.waitFor(10);
        driver.switchTo().frame(0);
        BrowserUtils.waitFor(4);
        activateCardPage.enterPinNumber(keys);
        activateCardPage.reEnterPinNumber(keys);
        activateCardPage.clickPinSubmitButton();
        driver.switchTo().window(secondWindowhandle);
        generatorEmail.clickHamburgerMenuThreeDots();
        generatorEmail.clickDeleteThisMessage();
    }

    @Test
    public void FreezeCard() {
        String username = "moseloway1900@gmail.com";
        String password = "Welcome!1";
        String frozenMessage = "your card is now frozen";
        String googlePassword = "Taylor!24680";
        BrowserUtils.waitFor(10);
        termsAndConditionsPage.clickRadioButton();
        termsAndConditionsPage.clickContinueButton();
        loginPage.clickEmailTextBox(username);
        loginPage.clickPasswordTextBox(password);
        BrowserUtils.waitFor(5);
        loginPage.clickSignInButton();
        BrowserUtils.waitFor(18);
        loginPage.clickSendVerification();
        ((JavascriptExecutor) driver).executeScript("window.open('https://www.google.com/?authuser=1')");
        BrowserUtils.waitFor(10);
        Set<String> handles = driver.getWindowHandles();
        String firstWindowhandle = driver.getWindowHandle();
        handles.remove(firstWindowhandle);
        String winHandle = handles.iterator().next();
        String secondWindowhandle = winHandle;
        driver.switchTo().window(secondWindowhandle);
        googlePage.clickSignInButton();
        googlePage.enterEmail(username);
        googlePage.clickNextButton();
        googlePage.enterPassword(googlePassword);
        googlePage.clickNextButtonTwo();
        googlePage.clickAppsIcon();
        driver.switchTo().frame(0);
        googlePage.clickGmailIcon();
        googlePage.clickVerificationEmail();
        BrowserUtils.waitFor(4);
        //driver.switchTo().defaultContent();
        googlePage.clickEmail(); //might move
        BrowserUtils.waitFor(3);
        emailVerificationPage.clickVerifyEmailButton();
        driver.switchTo().window(firstWindowhandle);
        BrowserUtils.waitFor(25);
        accountDetailsPage.clickagainHamburgerMenu();
        BrowserUtils.waitFor(3);
        accountDetailsPage.clickManageCardButton();
        BrowserUtils.waitFor(3);
        manageCardPage.clickFreezeMyCard();
        BrowserUtils.waitFor(3);
        manageCardPage.clickFreezeMyCardSlider();
        BrowserUtils.waitFor(5);
        //manageCardPage.getFrozenMessageText();
        //BrowserUtils.waitFor(3);
        Assert.assertEquals(manageCardPage.getFrozenMessageText(), frozenMessage);
        // System.out.println(manageCardPage.getFrozenMessageText());
        // System.out.println(frozenMessage);
        BrowserUtils.waitFor(3);
        manageCardPage.clickFreezeMyCardSlider();
        BrowserUtils.waitFor(3);

    }

    @Test
    public void OrderCustomCard() {
        String username = "moseloway1900@gmail.com";
        String password = "Welcome!1";
        String googlePassword = "Taylor!24680";
        BrowserUtils.waitFor(10);
        termsAndConditionsPage.clickRadioButton();
        termsAndConditionsPage.clickContinueButton();
        loginPage.clickEmailTextBox(username);
        loginPage.clickPasswordTextBox(password);
        BrowserUtils.waitFor(5);
        loginPage.clickSignInButton();
        BrowserUtils.waitFor(15);
        loginPage.clickSendVerification();
        ((JavascriptExecutor) driver).executeScript("window.open('https://www.google.com/?authuser=1')");
        BrowserUtils.waitFor(10);
        Set<String> handles = driver.getWindowHandles();
        String firstWindowhandle = driver.getWindowHandle();
        System.out.println(firstWindowhandle);
        handles.remove(firstWindowhandle);
        String winHandle = handles.iterator().next();
        String secondWindowhandle = winHandle;
        driver.switchTo().window(secondWindowhandle);
        System.out.println(secondWindowhandle);
        googlePage.clickSignInButton();
        googlePage.enterEmail(username);
        googlePage.clickNextButton();
        googlePage.enterPassword(googlePassword);
        googlePage.clickNextButtonTwo();
        googlePage.clickAppsIcon();
        driver.switchTo().frame(0);
        googlePage.clickGmailIcon();
        googlePage.clickVerificationEmail();
        BrowserUtils.waitFor(5);
        //driver.switchTo().defaultContent();
        googlePage.clickEmail(); //might move
        BrowserUtils.waitFor(3);
        emailVerificationPage.clickVerifyEmailButton();
        driver.switchTo().window(firstWindowhandle);
        BrowserUtils.waitFor(25);
        accountDetailsPage.clickagainHamburgerMenu();
        BrowserUtils.waitFor(3);
        accountDetailsPage.clickManageCardButton();
        manageCardPage.clickCustomizeCardButton();
        BrowserUtils.waitFor(2);
        customizeMyCardPage.clickAnimalsCustomButton();
        BrowserUtils.waitFor(6);
        customizeMyCardPage.clickLonghornCustomCard();
        BrowserUtils.waitFor(5);
        customizeMyCardPage.clickOrderCustomCardButton();
        BrowserUtils.waitFor(20);


    }

    @Test
    public void AnimatedVirtualCard() {
        String username = "moseloway1900@gmail.com";
        String password = "Welcome!1";
        String cardDetailsMessage = "Use your card details below for purchases.";
        String googlePassword = "Taylor!24680";
        BrowserUtils.waitFor(10);
        termsAndConditionsPage.clickRadioButton();
        termsAndConditionsPage.clickContinueButton();
        loginPage.clickEmailTextBox(username);
        loginPage.clickPasswordTextBox(password);
        BrowserUtils.waitFor(5);
        loginPage.clickSignInButton();
        BrowserUtils.waitFor(20);
        loginPage.clickSendVerification();
        ((JavascriptExecutor) driver).executeScript("window.open('https://www.google.com/?authuser=1')");
        BrowserUtils.waitFor(10);
        Set<String> handles = driver.getWindowHandles();
        String firstWindowhandle = driver.getWindowHandle();
        handles.remove(firstWindowhandle);
        String winHandle = handles.iterator().next();
        String secondWindowhandle = winHandle;
        driver.switchTo().window(secondWindowhandle);
        //System.out.println(secondWindowhandle);
        googlePage.clickSignInButton();
        googlePage.enterEmail(username);
        googlePage.clickNextButton();
        googlePage.enterPassword(googlePassword);
        googlePage.clickNextButtonTwo();
        googlePage.clickAppsIcon();
        driver.switchTo().frame(0);
        googlePage.clickGmailIcon();
        googlePage.clickVerificationEmail();
        BrowserUtils.waitFor(5);
        googlePage.clickEmail();
        BrowserUtils.waitFor(3);
        emailVerificationPage.clickVerifyEmailButton();
        driver.switchTo().window(firstWindowhandle);
        BrowserUtils.waitFor(20);
        accountDetailsPage.clickanimatedVirtualCard();
        Assert.assertEquals(accountDetailsPage.getCardDetailsMessage(), cardDetailsMessage);
        System.out.println(accountDetailsPage.getCardDetailsMessage());
        System.out.println(cardDetailsMessage);
        BrowserUtils.waitFor(8);
    }

    @Test
    public void SignUpForDirectDeposit() {
        String username = "moseloway1900@gmail.com";
        String password = "Welcome!1";
        String googlePassword = "Taylor!24680";
        String employer = "Sogeti USA";
        String SSNumber = "4839";
        String employerID = "4894590";
        String onItsWayMessage = "Direct deposit is on its way!";
        BrowserUtils.waitFor(10);
        termsAndConditionsPage.clickRadioButton();
        termsAndConditionsPage.clickContinueButton();
        loginPage.clickEmailTextBox(username);
        loginPage.clickPasswordTextBox(password);
        BrowserUtils.waitFor(5);
        loginPage.clickSignInButton();
        BrowserUtils.waitFor(15);
        loginPage.clickSendVerification();
        ((JavascriptExecutor) driver).executeScript("window.open('https://www.google.com/?authuser=1')");
        BrowserUtils.waitFor(10);
        Set<String> handles = driver.getWindowHandles();
        String firstWindowhandle = driver.getWindowHandle();
        System.out.println(firstWindowhandle);
        handles.remove(firstWindowhandle);
        String winHandle = handles.iterator().next();
        String secondWindowhandle = winHandle;
        driver.switchTo().window(secondWindowhandle);
        System.out.println(secondWindowhandle);
        googlePage.clickSignInButton();
        googlePage.enterEmail(username);
        googlePage.clickNextButton();
        googlePage.enterPassword(googlePassword);
        googlePage.clickNextButtonTwo();
        googlePage.clickAppsIcon();
        driver.switchTo().frame(0);
        googlePage.clickGmailIcon();
        googlePage.clickVerificationEmail();
        BrowserUtils.waitFor(5);
        //driver.switchTo().defaultContent();
        googlePage.clickEmail(); //might move
        BrowserUtils.waitFor(3);
        emailVerificationPage.clickVerifyEmailButton();
        driver.switchTo().window(firstWindowhandle);
        BrowserUtils.waitFor(27);
        accountDetailsPage.clickDirectDepositIcon();
        BrowserUtils.waitFor(4);
        accountDetailsPage.enterEmployerName(employer);
        BrowserUtils.waitFor(1);
        accountDetailsPage.clickDDSearchButton();
        BrowserUtils.waitFor(5);
        accountDetailsPage.clickSelectEmployerName();
        BrowserUtils.waitFor(4);
        directDepositPage.enterSSN(SSNumber);
        directDepositPage.enterEmployeeID(employerID);
        directDepositPage.clickContinueButton();
        BrowserUtils.waitFor(4);
        directDepositPage.clickFlateRateRadioButton();
        directDepositPage.enterDepositAmount();
        directDepositPage.clickSetupButtonComplete();
        BrowserUtils.waitFor(5);
        Assert.assertEquals(directDepositPage.getOnItsWayMessage(), onItsWayMessage);
        directDepositPage.clickDoneButton();
        BrowserUtils.waitFor(5);
    }

    @Test
    public void SendFeedback() {
        String username = "moseloway1900@gmail.com";
        String password = "Welcome!1";
        String googlePassword = "Taylor!24680";
        String feedbackMessage = "We appreciate your feedback";
        BrowserUtils.waitFor(10);
        termsAndConditionsPage.clickRadioButton();
        termsAndConditionsPage.clickContinueButton();
        loginPage.clickEmailTextBox(username);
        loginPage.clickPasswordTextBox(password);
        BrowserUtils.waitFor(5);
        loginPage.clickSignInButton();
        BrowserUtils.waitFor(20);
        loginPage.clickSendVerification();
        ((JavascriptExecutor) driver).executeScript("window.open('https://www.google.com/?authuser=1')");
        BrowserUtils.waitFor(10);
        Set<String> handles = driver.getWindowHandles();
        String firstWindowhandle = driver.getWindowHandle();
        System.out.println(firstWindowhandle);
        handles.remove(firstWindowhandle);
        String winHandle = handles.iterator().next();
        String secondWindowhandle = winHandle;
        driver.switchTo().window(secondWindowhandle);
        System.out.println(secondWindowhandle);
        googlePage.clickSignInButton();
        googlePage.enterEmail(username);
        googlePage.clickNextButton();
        googlePage.enterPassword(googlePassword);
        googlePage.clickNextButtonTwo();
        googlePage.clickAppsIcon();
        driver.switchTo().frame(0);
        googlePage.clickGmailIcon();
        googlePage.clickVerificationEmail();
        BrowserUtils.waitFor(8);
        //driver.switchTo().defaultContent();
        googlePage.clickEmail(); //might move
        BrowserUtils.waitFor(3);
        emailVerificationPage.clickVerifyEmailButton();
        driver.switchTo().window(firstWindowhandle);
        BrowserUtils.waitFor(25);
        accountDetailsPage.clickagainHamburgerMenu();
        feedbackPage.clickSendFeedbackButton();
        BrowserUtils.waitFor(4);
        feedbackPage.clickGoodBubbleIcon();
        BrowserUtils.waitFor(2);
        feedbackPage.enterCommentsInTextBox();
        BrowserUtils.waitFor(2);
        feedbackPage.clickAuthorizationBox();
        BrowserUtils.waitFor(2);
        feedbackPage.clickFeedbackSubmitButton();
        BrowserUtils.waitFor(8);
        Assert.assertEquals(feedbackPage.getFeedbackCavemanMessage(), feedbackMessage);
    }

    @Test
    public void MakePayment() {
        String username = "moseloway1900@gmail.com";
        String password = "Welcome!1";
        String googlePassword = "Taylor!24680";
        String employer = "ikea";
        BrowserUtils.waitFor(10);
        termsAndConditionsPage.clickRadioButton();
        termsAndConditionsPage.clickContinueButton();
        loginPage.clickEmailTextBox(username);
        loginPage.clickPasswordTextBox(password);
        BrowserUtils.waitFor(5);
        loginPage.clickSignInButton();
        BrowserUtils.waitFor(15);
        loginPage.clickSendVerification();
        ((JavascriptExecutor) driver).executeScript("window.open('https://www.google.com/?authuser=1')");
        BrowserUtils.waitFor(10);
        Set<String> handles = driver.getWindowHandles();
        String firstWindowhandle = driver.getWindowHandle();
        System.out.println(firstWindowhandle);
        handles.remove(firstWindowhandle);
        String winHandle = handles.iterator().next();
        String secondWindowhandle = winHandle;
        driver.switchTo().window(secondWindowhandle);
        System.out.println(secondWindowhandle);
        googlePage.clickSignInButton();
        googlePage.enterEmail(username);
        googlePage.clickNextButton();
        googlePage.enterPassword(googlePassword);
        googlePage.clickNextButtonTwo();
        googlePage.clickAppsIcon();
        driver.switchTo().frame(0);
        googlePage.clickGmailIcon();
        googlePage.clickVerificationEmail();
        BrowserUtils.waitFor(8);
        //driver.switchTo().defaultContent();
        googlePage.clickEmail(); //might move
        BrowserUtils.waitFor(3);
        emailVerificationPage.clickVerifyEmailButton();
        driver.switchTo().window(firstWindowhandle);
        BrowserUtils.waitFor(25);
        accountDetailsPage.clickPayBillsButton();
        BrowserUtils.waitFor(2);
        payBillsPage.enterEmployerInTextBox(employer);
        BrowserUtils.waitFor(2);
        payBillsPage.clickPayBillSearchButton();
        BrowserUtils.waitFor(2);
        payBillsPage.clickEmployerResult();
        BrowserUtils.waitFor(2);
        payBillsPage.enterAccountNumber();
        BrowserUtils.waitFor(2);
        payBillsPage.setPayBillContinueButton();
        BrowserUtils.waitFor(8);
        payBillsPage.enterDollarAmount();
        BrowserUtils.waitFor(2);
        payBillsPage.clickConfirmAmount();
        BrowserUtils.waitFor(2);
        payBillsPage.clickSubmitPayment();
        BrowserUtils.waitFor(10);
        payBillsPage.clickViewAccountButton();
        BrowserUtils.waitFor(5);
    }
    @Test
    public void TransferFunds() {
        String username = "moseloway1900@gmail.com";
        String password = "Welcome!1";
        String googlePassword = "Taylor!24680";
        String accountNumber = "283746";
        String confirmAccountNumber = "283746";
        String name = "Birlington";
        BrowserUtils.waitFor(10);
        termsAndConditionsPage.clickRadioButton();
        termsAndConditionsPage.clickContinueButton();
        loginPage.clickEmailTextBox(username);
        loginPage.clickPasswordTextBox(password);
        BrowserUtils.waitFor(5);
        loginPage.clickSignInButton();
        BrowserUtils.waitFor(25);
        loginPage.clickSendVerification();
        ((JavascriptExecutor) driver).executeScript("window.open('https://www.google.com/?authuser=1')");
        BrowserUtils.waitFor(10);
        Set<String> handles = driver.getWindowHandles();
        String firstWindowhandle = driver.getWindowHandle();
        System.out.println(firstWindowhandle);
        handles.remove(firstWindowhandle);
        String winHandle = handles.iterator().next();
        String secondWindowhandle = winHandle;
        driver.switchTo().window(secondWindowhandle);
        System.out.println(secondWindowhandle);
        googlePage.clickSignInButton();
        googlePage.enterEmail(username);
        googlePage.clickNextButton();
        googlePage.enterPassword(googlePassword);
        googlePage.clickNextButtonTwo();
        googlePage.clickAppsIcon();
        driver.switchTo().frame(0);
        BrowserUtils.waitFor(2);
        googlePage.clickGmailIcon();
        googlePage.clickVerificationEmail();
        BrowserUtils.waitFor(8);
        googlePage.clickEmail(); //might move
        BrowserUtils.waitFor(3);
        emailVerificationPage.clickVerifyEmailButton();
        driver.switchTo().window(firstWindowhandle);
        BrowserUtils.waitFor(25);
        accountDetailsPage.clickTransferFundsButton();
        BrowserUtils.waitFor(5);
        transferFundsPage.clickaddExternalAccountButton();
        transferFundsPage.enterRoutingNumber();
        BrowserUtils.waitFor(2);
        transferFundsPage.enterAccountNumber(accountNumber);
        BrowserUtils.waitFor(2);
        transferFundsPage.confirmAccountNumber(confirmAccountNumber);
        BrowserUtils.waitFor(1);
        transferFundsPage.clickTransferFundsContinueButton();
        BrowserUtils.waitFor(5);
        transferFundsPage.enterAccountNickName(name);
        BrowserUtils.waitFor(1);
        transferFundsPage.clickAuthorizationButton();
        BrowserUtils.waitFor(1);
        transferFundsPage.clickAddAccount();
        BrowserUtils.waitFor(80);
    }
    @Test
    public void MyProfileValidation() {
        String username = "moseloway1900@gmail.com";
        String password = "Welcome!1";
        String googlePassword = "Taylor!24680";
        String accountNumber = "244106503240";
        String routingNumber = "101019084";
        String DOB = "12-09-2000";
        String phoneNumber = "555-894-3984";
        String homeAddress = "4983 Diesel St";
        BrowserUtils.waitFor(10);
        termsAndConditionsPage.clickRadioButton();
        termsAndConditionsPage.clickContinueButton();
        loginPage.clickEmailTextBox(username);
        loginPage.clickPasswordTextBox(password);
        BrowserUtils.waitFor(5);
        loginPage.clickSignInButton();
        BrowserUtils.waitFor(20);
        loginPage.clickSendVerification();
        ((JavascriptExecutor) driver).executeScript("window.open('https://www.google.com/?authuser=1')");
        BrowserUtils.waitFor(10);
        Set<String> handles = driver.getWindowHandles();
        String firstWindowhandle = driver.getWindowHandle();
        System.out.println(firstWindowhandle);
        handles.remove(firstWindowhandle);
        String winHandle = handles.iterator().next();
        String secondWindowhandle = winHandle;
        driver.switchTo().window(secondWindowhandle);
        System.out.println(secondWindowhandle);
        googlePage.clickSignInButton();
        googlePage.enterEmail(username);
        googlePage.clickNextButton();
        googlePage.enterPassword(googlePassword);
        googlePage.clickNextButtonTwo();
        googlePage.clickAppsIcon();
        driver.switchTo().frame(0);
        googlePage.clickGmailIcon();
        googlePage.clickVerificationEmail();
        BrowserUtils.waitFor(9);
        googlePage.clickEmail(); //might move
        BrowserUtils.waitFor(3);
        emailVerificationPage.clickVerifyEmailButton();
        driver.switchTo().window(firstWindowhandle);
        BrowserUtils.waitFor(25);
        accountDetailsPage.clickagainHamburgerMenu();
        BrowserUtils.waitFor(2);
        accountDetailsPage.clickProfileTab();
        BrowserUtils.waitFor(4);
        profilePage.clickAccountInfoTab();
        BrowserUtils.waitFor(7);
        profilePage.getDOB();
        Assert.assertEquals(profilePage.getDOB(),DOB);
        profilePage.getRoutingNumber();
        Assert.assertEquals(profilePage.getRoutingNumber(),routingNumber);
        profilePage.getAccountNumber();
        Assert.assertEquals(profilePage.getAccountNumber(),accountNumber);
        profilePage.clickContactInfoTab();
        BrowserUtils.waitFor(2);
        profilePage.getPhoneNumber();
        Assert.assertEquals(profilePage.getPhoneNumber(),phoneNumber);
        profilePage.clickAddressInfo();
        profilePage.getHomeAddress();
        BrowserUtils.waitFor(2);
        Assert.assertEquals(profilePage.getHomeAddress(),homeAddress);
        BrowserUtils.waitFor(5);
    }
    @Test
    public void NotificationsTest() {
        String username = "moseloway1900@gmail.com";
        String password = "Welcome!1";
        String googlePassword = "Taylor!24680";
        BrowserUtils.waitFor(10);
        termsAndConditionsPage.clickRadioButton();
        termsAndConditionsPage.clickContinueButton();
        loginPage.clickEmailTextBox(username);
        loginPage.clickPasswordTextBox(password);
        BrowserUtils.waitFor(5);
        loginPage.clickSignInButton();
        BrowserUtils.waitFor(20);
        loginPage.clickSendVerification();
        ((JavascriptExecutor) driver).executeScript("window.open('https://www.google.com/?authuser=1')");
        BrowserUtils.waitFor(10);
        Set<String> handles = driver.getWindowHandles();
        String firstWindowhandle = driver.getWindowHandle();
        System.out.println(firstWindowhandle);
        handles.remove(firstWindowhandle);
        String winHandle = handles.iterator().next();
        String secondWindowhandle = winHandle;
        driver.switchTo().window(secondWindowhandle);
        System.out.println(secondWindowhandle);
        googlePage.clickSignInButton();
        googlePage.enterEmail(username);
        googlePage.clickNextButton();
        googlePage.enterPassword(googlePassword);
        googlePage.clickNextButtonTwo();
        googlePage.clickAppsIcon();
        driver.switchTo().frame(0);
        googlePage.clickGmailIcon();
        googlePage.clickVerificationEmail();
        BrowserUtils.waitFor(9);
        googlePage.clickEmail(); //might move
        BrowserUtils.waitFor(3);
        emailVerificationPage.clickVerifyEmailButton();
        driver.switchTo().window(firstWindowhandle);
        BrowserUtils.waitFor(25);
        accountDetailsPage.clickagainHamburgerMenu();
        BrowserUtils.waitFor(2);
        accountDetailsPage.clickProfileTab();
        BrowserUtils.waitFor(5);
        profilePage.clickNotificationTab();
        BrowserUtils.waitFor(7);
        profilePage.clickAccountNotificationsTab();
        BrowserUtils.waitFor(2);
        profilePage.clickdailyAvailableBalanceNoticeSlider();
        BrowserUtils.waitFor(2);
        profilePage.clickmoneyhasbeenaddedtoyouraccountSlider();
        BrowserUtils.waitFor(2);
        profilePage.clickaNotificationWhenYourAccountHasAnNegativeBalance();
        BrowserUtils.waitFor(3);
        profilePage.clickAccountNotificationsTab();
        BrowserUtils.waitFor(2);
        profilePage.clickdailyAvailableBalanceNoticeSlider();
        BrowserUtils.waitFor(2);
        profilePage.clickmoneyhasbeenaddedtoyouraccountSlider();
        BrowserUtils.waitFor(2);
        profilePage.clickaNotificationWhenYourAccountHasAnNegativeBalance();
        BrowserUtils.waitFor(2);
        profilePage.clickDoneButton();
        BrowserUtils.waitFor(5);
    }
}